### ISSUE TITLE
Consider renaming `.data()` to `.encode()`

### ISSUE THREAD

**Issue by Gozala** [ipld/js-ipld-stack#4]
I would like to advocate for a name that is clearer than `.data()` as I find it very confusing. In fact intuitively I expect it to return decodec object rather than encoded bytes while it's reverse. 

I would suggest calling it `.encode()` as result is often referred to as "binary encoded data". In fact it's also what the function does if `Block` is constructed out of an object.

**Comment by mikeal** [comment]
This would align the names with the codec implementation and have better symmetry. +1 from me.
