### ISSUE TITLE
Specific constructors instead of generic ones.

### ISSUE THREAD

**Issue by Gozala** [ipld/js-ipld-stack#5]
I would very much prefer if API `Block.from` was split into two different methods:

- `Block.encoder(Object, codec, algorithm)`
- `Block.decoder(Buffer, codec, algorithm)`

Or other names as that saves reader for side-trips when attempting to identify what is `bla` when seeing `Block.from(bla, codec, algorithm)`.

**Comment by mikeal** [comment]
I added the dual (Object | Buffer) stuff to the `from` API a bit late and the more I look at it the more I don’t like how fancy it is with the type checking. I’m +1 on this change.
